
version: 2

models:
    - name: stg_distribution_centers
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests: 
                - unique
                - not_null

    - name: stg_inventory_items
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
